services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: api-juguete-dragonfly
    ulimits:
      memlock: -1
    volumes:
      - ./data:/data
    networks:
      - api-juguete

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-juguete-bun
    depends_on:
      - dragonfly
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: ["bun", "start"]
    networks:
      - api-juguete

networks:
  api-juguete:
    driver: bridge
