services:
  dragonfly:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest
    container_name: api-juguete-dragonfly
    ports:
      - "6379:6379"
    ulimits:
      memlock: -1
    volumes:
      - ./data:/data
